version = 1

exclude_patterns = [
  "frontend/wailsjs/**/*.js",
  "frontend/wailsjs/**/*.ts"
]

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/ru3bix/manimbook-reader"

[[transformers]]
name = "prettier"