// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {book} from '../models';

export function GetBook():Promise<book.Book>;

export function GetPort():Promise<number>;
